version: '3.3'

volumes: 
  mongodata:
  node_modules_service:

services: 
  mongodb:
    image: mongo:5.0.9
    restart: unless-stopped
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes: 
      - mongodata:/data/db
      - ./backup:/backup
    ports: 
      - 27017:27017

  service:
    build:
      context: .
      target: dev
    volumes:
      - node_modules_service:/app/node_modules
      - ./:/app
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - 3000:3000
      # debug
      - 9229:9229
    entrypoint: ["npm", "run", "start:debug"]
    depends_on:
      - mongodb

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD}
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_SERVER=mongodb
    links:
      - mongodb